apiVersion: v1
kind: Service
metadata:
  name: verteilte-systeme-service
spec:
  selector:
    app: verteilte-systeme
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000